- name: Expense Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable Nodejs default Version
      ansible.builtin.shell: cmd="dnf module disable nodejs -y"
    - name: Enable NodeJS 18 version
      ansible.builtin.shell: cmd="dnf module enable nodejs:18 -y"
    - name: install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy Backend Service File
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add Application User
      ansible.builtin.user:
        name: expense
    - name: Delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Create App directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.backend.zip
        dest: /app
        remote_src: yes
    - name: download nodejs Dependencies
      ansible.builtin.shell:
        cmd: npm install
        chdir: /app
    - name: install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: load schema
      ansible.builtin.shell:
        cmd: mysql -h mysql-dev.rubydevops.cloud -uroot -p{{ MYSQL_ROOT_PASSWORD }} </app/schema/backend.sql
    - name: Restart Backend Service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes
