- name: Disable Nodejs default Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS 20 version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copy Backend Service File
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add Application User
  ansible.builtin.user:
    name: expense

- name: Import Common Role - APP pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /app
    component: backend

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present


- name: Load schema
  ansible.builtin.shell:
      mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend-{{env}}.DB_HOST', region='us-east-1' ) }}
      -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }}
      -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }}
      < /app/schema/backend.sql


- name: Restart Backend Service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
