- name: import common role - APP pre-requisites
  import_role:
    name: common

  vars:
    component: frontend

- name: Delete old app directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Create App directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_dir }}"
    remote_src: yes
